package TPPDekuBot;

public enum PWTType {
    RANDOM, KANTO_GYM, JOHTO_GYM, HOENN_GYM, SINNOH_GYM, UNOVA_GYM, CHAMPIONS, SPECIAL, TYPE_NORMAL, TYPE_FIRE, TYPE_FIGHTING, TYPE_WATER, TYPE_FLYING, TYPE_GRASS, TYPE_POISON, TYPE_ELECTRIC, TYPE_GROUND, TYPE_PSYCHIC, TYPE_ROCK, TYPE_ICE, TYPE_BUG, TYPE_DRAGON, TYPE_GHOST, TYPE_DARK, TYPE_STEEL, TYPE_FAIRY
}

enum PWTClass {
    NORMAL, MASTER
}
